[package]
name = "workbench2"
version = "0.2.0"
authors = ["Bohdan Khorolets <bogdan@khorolets.com>"]

[dependencies]
iron = "*"
router = "*"
mount = "*"
staticfile = "*"
hyper = "*"
tera = "*"
chrono = "0.3.0"
serde_json = "*"
